const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const {spawn}=require('node:child_process');
const {pathToFileURL}=require('node:url');
const path=require('node:path');
(async()=>{
 const server=spawn('python3',['-m','http.server','4174','--bind','127.0.0.1','--directory','.local-preview/media-output'],{stdio:'ignore'});
 let browser;
 try {
  for(let attempt=0;attempt<30;attempt++){
   try {const response=await fetch('http://127.0.0.1:4174'); if(response.ok) break;} catch {}
   if(attempt===29) throw Error('Media fixture server failed to start');
   await new Promise(resolve=>setTimeout(resolve,100));
  }
  browser=await chromium.launch({headless:true});
  const page=await browser.newPage(); const errors=[]; page.on('pageerror',e=>errors.push(e.message));
  await page.goto('http://127.0.0.1:4174');
  await page.waitForSelector('[data-aid-player][data-state="ready"]');
  assert.equal(await page.locator('[data-aid-content]').getAttribute('src'),null);
  await page.locator('[data-aid-play]').click();
  await page.waitForSelector('[data-state="disclosure"]');
  assert.equal(await page.locator('[data-aid-content]').getAttribute('src'),null);
  await page.waitForSelector('[data-state="content"]');
  await page.waitForFunction(()=>document.querySelector('[data-aid-content]').currentTime>0);
  await page.waitForFunction(()=>document.querySelector('[data-aid-cue]').textContent==='Test caption text');
  await page.getByRole('combobox',{name:'Captions',exact:true}).selectOption('-1');
  assert.equal(await page.locator('[data-aid-cue]').textContent(),'');
  await page.locator('[data-aid-play]').click();
  assert.equal(await page.locator('[data-aid-content]').evaluate(e=>e.paused),true);
  await page.locator('[data-aid-player]').evaluate(e=>e.dataset.source='changed.wav');
  await page.waitForSelector('[data-state="invalid"]');
  assert.equal(await page.locator('[data-aid-content]').getAttribute('src'),null);
  await page.reload(); await page.route('**/notice.wav',r=>r.abort());
  await page.locator('[data-aid-play]').click();
  await page.waitForSelector('[data-state="error"]');
  assert.equal(await page.locator('[data-aid-content]').getAttribute('src'),null);
  const nojs=await browser.newPage({javaScriptEnabled:false}); await nojs.goto('http://127.0.0.1:4174');
  assert.equal(await nojs.locator('[data-aid-play]').isDisabled(),true);
  assert.equal(await nojs.locator('[data-aid-content]').getAttribute('src'),null);
  assert.equal(await nojs.locator('.aid-notice').isVisible(),true);
  await page.goto('http://127.0.0.1:4174/video.html');
  await page.locator('[data-aid-play]').click();
  await page.waitForFunction(()=>document.querySelector('video').currentTime>0);
  await page.waitForFunction(()=>document.querySelector('video').textTracks[0].activeCues?.length===1);
  assert.equal(await page.locator('video').evaluate(e=>e.textTracks[0].mode),'showing');
  await page.locator('[data-aid-play]').click();
  await page.getByRole('combobox',{name:'Captions',exact:true}).selectOption('-1');
  assert.equal(await page.locator('video').evaluate(e=>e.textTracks[0].mode),'disabled');
  await page.getByRole('combobox',{name:'Captions',exact:true}).selectOption('0');
  await page.getByRole('button',{name:'Fullscreen',exact:true}).click();
  await page.waitForFunction(()=>document.fullscreenElement?.classList.contains('aid-media'));
  assert.equal(await page.locator('.aid-notice').isVisible(),true);
  await page.screenshot({path:'.local-preview/video-fullscreen.png'});
  await page.getByRole('button',{name:'Exit fullscreen',exact:true}).click();
  for (const width of [390,1440]) {
   await nojs.setViewportSize({width,height:800});
   await nojs.goto('http://127.0.0.1:4174/chat.html#composer');
   const notice=nojs.locator('.aid-notice');
   assert.equal(await notice.textContent(),'You are interacting with AI.');
   const bounds=await notice.boundingBox();
   assert.ok(bounds.y>=0 && bounds.y+bounds.height<=800,'Chat notice remains visible at deep-linked composer');
   await nojs.getByRole('textbox',{name:'Message'}).focus();
   assert.equal(await notice.isVisible(),true);
  }
  await page.goto('http://127.0.0.1:4174/chat.html');
  await page.evaluate(()=>{
   const old=document.querySelector('.aid-chat');
   const resumed=old.cloneNode(true);
   resumed.querySelector('[role=log]').textContent='Resumed test conversation';
   old.replaceWith(resumed);
  });
  await page.getByRole('textbox',{name:'Message'}).fill('Test message');
  await page.getByRole('button',{name:'Send test message'}).click();
  assert.equal(await page.locator('.aid-notice').count(),1);
  assert.equal(await page.locator('.aid-notice').isVisible(),true);
  await page.goto('http://127.0.0.1:4174/dynamic.html');
  assert.equal(await page.locator('#publication .aid-notice').count(),1);
  await page.getByRole('button',{name:'Publish recorded update',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('#publication').textContent.includes('Second version.'));
  assert.equal(await page.locator('#publication .aid-notice').count(),1);
  assert.equal(await page.locator('#publication .aid-notice').isVisible(),true);
  await page.getByRole('button',{name:'Try unrecorded update',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('[role=status]').textContent.includes('Update held'));
  assert.ok((await page.locator('#publication').textContent()).includes('Second version.'));
  assert.equal(await page.locator('#publication .aid-notice').count(),1);
  await nojs.goto('http://127.0.0.1:4174/dynamic.html');
  assert.equal(await nojs.locator('#publication .aid-notice').isVisible(),true);
  const offline=await browser.newPage({javaScriptEnabled:false,viewport:{width:390,height:800}});
  const network=[];
  offline.on('request',request=>{if(/^https?:/.test(request.url())) network.push(request.url());});
  await offline.goto(pathToFileURL(path.resolve('.local-preview/media-output/export.html')).href);
  assert.equal(await offline.title(),'Portable publication');
  assert.equal(await offline.locator('.aid-notice').count(),2);
  assert.ok(await offline.locator('img').evaluate(e=>e.complete && e.naturalWidth===160));
  for(const notice of await offline.locator('.aid-notice').all()) assert.equal(await notice.isVisible(),true);
  await offline.emulateMedia({media:'print'});
  for(const notice of await offline.locator('.aid-notice').all()) assert.equal(await notice.isVisible(),true);
  assert.deepEqual(network,[],'Portable document must load without external requests');
  await offline.close();
  assert.deepEqual(errors,[]);
  console.log('PASS: offline document images and print notices; recorded dynamic publication and held stale update; audio/video captions and video fullscreen; chat first rendering, deep links, mobile and resumed template; real audio sequencing, pause, configuration invalidation, notice failure, no-JS visibility. Silence fixture does not validate spoken wording.');
 } finally {if(browser) await browser.close(); server.kill();}
})().catch(e=>{console.error(e);process.exit(1)});
